/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as AuthRouteImport } from "./routes/_auth";
import { Route as AuthIndexRouteImport } from "./routes/_auth.index";
import { Route as ApiAuthSplatRouteImport } from "./routes/api.auth.$";
import { Route as LoginRouteImport } from "./routes/login";

const LoginRoute = LoginRouteImport.update({
	id: "/login",
	path: "/login",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthRoute = AuthRouteImport.update({
	id: "/_auth",
	getParentRoute: () => rootRouteImport,
} as any);
const AuthIndexRoute = AuthIndexRouteImport.update({
	id: "/",
	path: "/",
	getParentRoute: () => AuthRoute,
} as any);
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
	id: "/api/auth/$",
	path: "/api/auth/$",
	getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
	"/login": typeof LoginRoute;
	"/": typeof AuthIndexRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesByTo {
	"/login": typeof LoginRoute;
	"/": typeof AuthIndexRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRoutesById {
	__root__: typeof rootRouteImport;
	"/_auth": typeof AuthRouteWithChildren;
	"/login": typeof LoginRoute;
	"/_auth/": typeof AuthIndexRoute;
	"/api/auth/$": typeof ApiAuthSplatRoute;
}
export interface FileRouteTypes {
	fileRoutesByFullPath: FileRoutesByFullPath;
	fullPaths: "/login" | "/" | "/api/auth/$";
	fileRoutesByTo: FileRoutesByTo;
	to: "/login" | "/" | "/api/auth/$";
	id: "__root__" | "/_auth" | "/login" | "/_auth/" | "/api/auth/$";
	fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
	AuthRoute: typeof AuthRouteWithChildren;
	LoginRoute: typeof LoginRoute;
	ApiAuthSplatRoute: typeof ApiAuthSplatRoute;
}

declare module "@tanstack/react-router" {
	interface FileRoutesByPath {
		"/login": {
			id: "/login";
			path: "/login";
			fullPath: "/login";
			preLoaderRoute: typeof LoginRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_auth": {
			id: "/_auth";
			path: "";
			fullPath: "";
			preLoaderRoute: typeof AuthRouteImport;
			parentRoute: typeof rootRouteImport;
		};
		"/_auth/": {
			id: "/_auth/";
			path: "/";
			fullPath: "/";
			preLoaderRoute: typeof AuthIndexRouteImport;
			parentRoute: typeof AuthRoute;
		};
		"/api/auth/$": {
			id: "/api/auth/$";
			path: "/api/auth/$";
			fullPath: "/api/auth/$";
			preLoaderRoute: typeof ApiAuthSplatRouteImport;
			parentRoute: typeof rootRouteImport;
		};
	}
}

interface AuthRouteChildren {
	AuthIndexRoute: typeof AuthIndexRoute;
}

const AuthRouteChildren: AuthRouteChildren = {
	AuthIndexRoute: AuthIndexRoute,
};

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren);

const rootRouteChildren: RootRouteChildren = {
	AuthRoute: AuthRouteWithChildren,
	LoginRoute: LoginRoute,
	ApiAuthSplatRoute: ApiAuthSplatRoute,
};
export const routeTree = rootRouteImport
	._addFileChildren(rootRouteChildren)
	._addFileTypes<FileRouteTypes>();

import type { createStart } from "@tanstack/react-start";
import type { getRouter } from "./router.tsx";
declare module "@tanstack/react-start" {
	interface Register {
		ssr: true;
		router: Awaited<ReturnType<typeof getRouter>>;
	}
}
